// scripts/generateIconPresetTexts.js
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(process.cwd(), "assets/iconPresets");
const OUT_FILE = path.join(process.cwd(), "src/generated/iconPresetTexts.ts");

function main() {
  if (!fs.existsSync(SRC_DIR)) {
    console.error("[generateIconPresetTexts] Not found:", SRC_DIR);
    process.exit(1);
  }

  const entries = {};

  for (const file of fs.readdirSync(SRC_DIR)) {
    if (!file.toLowerCase().endsWith(".svg")) continue;

    const key = file.replace(/\.svg$/i, "");
    const fullPath = path.join(SRC_DIR, file);
    const text = fs.readFileSync(fullPath, "utf8");

    entries[key] = text;
  }

  // JSON.stringify したオブジェクトをそのまま TS のオブジェクトリテラルとして書き出す
  const tsSource =
    `// Auto-generated by scripts/generateIconPresetTexts.js\n` +
    `// DO NOT EDIT MANUALLY\n\n` +
    `export const iconPresetTexts: Record<string, string> = ` +
    JSON.stringify(entries, null, 2) +
    `;\n\n` +
    `export type IconPresetKey = keyof typeof iconPresetTexts;\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, tsSource);

  console.log("[generateIconPresetTexts] Generated:", OUT_FILE);
}

main();
